import type { Job } from "./types";

export const sampleJobs: Job[] = [
  {
    id: "sample-1",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    slug: "senior-ai-engineer-neural-works-berlin",
    status: "live",
    title: "Senior AI Engineer",
    company_name: "Neural Works",
    company_logo_url: null,
    location_city: "berlin",
    country: "DE",
    work_mode: "hybrid",
    employment_type: "full-time",
    role_type: "ai-engineer",
    seniority: "senior",
    description_markdown:
      "Wir bauen produktionsreife LLM-Systeme fuer B2B-Kunden.\n\n**Deine Aufgaben**\n\n- RAG-Pipelines entwickeln\n- Evaluation und Monitoring verbessern\n- Eng mit Product und Engineering arbeiten\n\n**Stack:** Python, TypeScript, Postgres, Vercel, OpenAI APIs.",
    apply_url: "https://example.com/apply",
    contact_email: "talent@example.com",
    salary_min: 85000,
    salary_max: 115000,
    salary_currency: "EUR",
    tags: ["Python", "LLM", "RAG", "TypeScript"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28).toISOString(),
  },
  {
    id: "sample-2",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    slug: "machine-learning-engineer-alpine-data-zurich",
    status: "live",
    title: "Machine Learning Engineer",
    company_name: "Alpine Data",
    company_logo_url: null,
    location_city: "zurich",
    country: "CH",
    work_mode: "onsite",
    employment_type: "full-time",
    role_type: "machine-learning",
    seniority: "mid",
    description_markdown:
      "Alpine Data sucht ML Engineering Verstaerkung fuer Forecasting-Produkte im B2B-SaaS-Umfeld.\n\n- Modelle produktionsnah betreiben\n- Feature Pipelines weiterentwickeln\n- Mit Data und Backend Teams zusammenarbeiten",
    apply_url: "https://example.com/apply-ml",
    contact_email: "jobs@example.com",
    salary_min: 105000,
    salary_max: 135000,
    salary_currency: "CHF",
    tags: ["Python", "MLOps", "Data Platform"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
  {
    id: "sample-3",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    slug: "frontend-platform-engineer-remote-dach",
    status: "live",
    title: "Frontend Platform Engineer",
    company_name: "Layer Labs",
    company_logo_url: null,
    location_city: "remote-dach",
    country: "DE",
    work_mode: "remote",
    employment_type: "full-time",
    role_type: "software-engineering",
    seniority: "senior",
    description_markdown:
      "Du entwickelst die Frontend-Plattform fuer AI-native Workflows und arbeitest an Design System, Performance und Developer Experience.",
    apply_url: "https://example.com/apply-fe",
    contact_email: "people@example.com",
    salary_min: 78000,
    salary_max: 98000,
    salary_currency: "EUR",
    tags: ["React", "TypeScript", "Next.js"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 23).toISOString(),
  },
  {
    id: "sample-4",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    slug: "llm-product-engineer-cortex-berlin",
    status: "live",
    title: "LLM Product Engineer",
    company_name: "Cortex Berlin",
    company_logo_url: null,
    location_city: "berlin",
    country: "DE",
    work_mode: "hybrid",
    employment_type: "full-time",
    role_type: "product",
    seniority: "senior",
    description_markdown:
      "Cortex Berlin baut AI-native Produktivitaetssoftware fuer regulierte Teams.\n\n**Du arbeitest an**\n\n- Prototypen fuer neue LLM-Workflows\n- Nutzernahem Prompt- und Evaluation-Design\n- Schnittstellen zwischen Product, Design und Engineering\n\nGesucht wird ein produktnaher Engineer mit starkem Gespuer fuer UX und technische Machbarkeit.",
    apply_url: "https://example.com/apply-product",
    contact_email: "hiring@example.com",
    salary_min: 90000,
    salary_max: 120000,
    salary_currency: "EUR",
    tags: ["LLM", "React", "TypeScript", "Product"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
  },
  {
    id: "sample-5",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    slug: "data-platform-engineer-vienna-signal",
    status: "live",
    title: "Data Platform Engineer",
    company_name: "Vienna Signal",
    company_logo_url: null,
    location_city: "vienna",
    country: "AT",
    work_mode: "hybrid",
    employment_type: "full-time",
    role_type: "data-engineering",
    seniority: "mid",
    description_markdown:
      "Vienna Signal entwickelt Datenplattformen fuer industrielle AI-Anwendungen.\n\n- Batch- und Streaming-Pipelines bauen\n- Datenqualitaet und Observability verbessern\n- Eng mit ML Engineers und Backend Teams arbeiten\n\nDer Stack umfasst Python, Postgres, dbt, Cloud-Infrastruktur und moderne Analytics-Tools.",
    apply_url: "https://example.com/apply-data",
    contact_email: "jobs@example.at",
    salary_min: 70000,
    salary_max: 92000,
    salary_currency: "EUR",
    tags: ["Python", "Data Platform", "Cloud", "MLOps"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 27).toISOString(),
  },
  {
    id: "sample-6",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    slug: "ai-security-engineer-hamburg-guardrail",
    status: "live",
    title: "AI Security Engineer",
    company_name: "Guardrail Systems",
    company_logo_url: null,
    location_city: "hamburg",
    country: "DE",
    work_mode: "remote",
    employment_type: "full-time",
    role_type: "security",
    seniority: "lead",
    description_markdown:
      "Guardrail Systems sucht Security-Erfahrung fuer AI-Produkte im Enterprise-Umfeld.\n\n**Fokus**\n\n- Threat Modeling fuer LLM-Features\n- Sicherheitsreviews von AI-Workflows\n- Guardrails, Logging und Incident-Prozesse\n\nIdeal fuer jemanden, der Security Engineering und moderne AI-Systeme zusammenbringt.",
    apply_url: "https://example.com/apply-security",
    contact_email: "security-hiring@example.com",
    salary_min: 98000,
    salary_max: 132000,
    salary_currency: "EUR",
    tags: ["Security", "LLM", "Cloud"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 26).toISOString(),
  },
  {
    id: "sample-7",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    slug: "computer-vision-engineer-munich-autonomy",
    status: "live",
    title: "Computer Vision Engineer",
    company_name: "Munich Autonomy",
    company_logo_url: null,
    location_city: "munich",
    country: "DE",
    work_mode: "onsite",
    employment_type: "full-time",
    role_type: "machine-learning",
    seniority: "senior",
    description_markdown:
      "Munich Autonomy arbeitet an visueller Wahrnehmung fuer industrielle Robotik.\n\n- Detection- und Tracking-Modelle verbessern\n- Trainingsdaten und Modellmetriken auswerten\n- Modelle in produktionsnahe Systeme integrieren\n\nErfahrung mit Python, Computer Vision und robustem Software Engineering ist wichtig.",
    apply_url: "https://example.com/apply-cv",
    contact_email: "talent@example.de",
    salary_min: 88000,
    salary_max: 118000,
    salary_currency: "EUR",
    tags: ["Python", "Computer Vision", "MLOps"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 6).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 24).toISOString(),
  },
  {
    id: "sample-8",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    slug: "full-stack-ai-engineer-rhine-labs-cologne",
    status: "live",
    title: "Full-Stack AI Engineer",
    company_name: "Rhine Labs",
    company_logo_url: null,
    location_city: "cologne",
    country: "DE",
    work_mode: "hybrid",
    employment_type: "full-time",
    role_type: "software-engineering",
    seniority: "mid",
    description_markdown:
      "Rhine Labs sucht Full-Stack-Verstaerkung fuer AI-gestuetzte B2B-Tools.\n\n- Next.js-Features entwickeln\n- LLM-Funktionen in bestehende Workflows integrieren\n- Gemeinsam mit Backend und Customer Success iterieren\n\nDer Stack ist TypeScript, React, Postgres und moderne AI APIs.",
    apply_url: "https://example.com/apply-fullstack",
    contact_email: "hello@example.de",
    salary_min: 72000,
    salary_max: 94000,
    salary_currency: "EUR",
    tags: ["React", "TypeScript", "Next.js", "LLM"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 22).toISOString(),
  },
];
