import type { Job } from "./types";

export const sampleJobs: Job[] = [
  {
    id: "sample-1",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    slug: "senior-ai-engineer-neural-works-berlin",
    status: "live",
    title: "Senior AI Engineer",
    company_name: "Neural Works",
    company_logo_url: null,
    location_city: "berlin",
    country: "DE",
    work_mode: "hybrid",
    employment_type: "full-time",
    role_type: "ai-engineer",
    seniority: "senior",
    description_markdown:
      "Wir bauen produktionsreife LLM-Systeme fuer B2B-Kunden.\n\n**Deine Aufgaben**\n\n- RAG-Pipelines entwickeln\n- Evaluation und Monitoring verbessern\n- Eng mit Product und Engineering arbeiten\n\n**Stack:** Python, TypeScript, Postgres, Vercel, OpenAI APIs.",
    apply_url: "https://example.com/apply",
    contact_email: "talent@example.com",
    salary_min: 85000,
    salary_max: 115000,
    salary_currency: "EUR",
    tags: ["Python", "LLM", "RAG", "TypeScript"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 28).toISOString(),
  },
  {
    id: "sample-2",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    slug: "machine-learning-engineer-alpine-data-zurich",
    status: "live",
    title: "Machine Learning Engineer",
    company_name: "Alpine Data",
    company_logo_url: null,
    location_city: "zurich",
    country: "CH",
    work_mode: "onsite",
    employment_type: "full-time",
    role_type: "machine-learning",
    seniority: "mid",
    description_markdown:
      "Alpine Data sucht ML Engineering Verstaerkung fuer Forecasting-Produkte im B2B-SaaS-Umfeld.\n\n- Modelle produktionsnah betreiben\n- Feature Pipelines weiterentwickeln\n- Mit Data und Backend Teams zusammenarbeiten",
    apply_url: "https://example.com/apply-ml",
    contact_email: "jobs@example.com",
    salary_min: 105000,
    salary_max: 135000,
    salary_currency: "CHF",
    tags: ["Python", "MLOps", "Data Platform"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25).toISOString(),
  },
  {
    id: "sample-3",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    slug: "frontend-platform-engineer-remote-dach",
    status: "live",
    title: "Frontend Platform Engineer",
    company_name: "Layer Labs",
    company_logo_url: null,
    location_city: "remote-dach",
    country: "DE",
    work_mode: "remote",
    employment_type: "full-time",
    role_type: "software-engineering",
    seniority: "senior",
    description_markdown:
      "Du entwickelst die Frontend-Plattform fuer AI-native Workflows und arbeitest an Design System, Performance und Developer Experience.",
    apply_url: "https://example.com/apply-fe",
    contact_email: "people@example.com",
    salary_min: 78000,
    salary_max: 98000,
    salary_currency: "EUR",
    tags: ["React", "TypeScript", "Next.js"],
    published_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    expires_at: new Date(Date.now() + 1000 * 60 * 60 * 24 * 23).toISOString(),
  },
];
